locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: proceed_to_checkout
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Proceed To Checkout
        index: 0
        uses: 8
      - mode: text
        value: Proceed to checkout
        index: 0
        uses: -1
      - mode: text
        value: proceed to checkout
        index: 0
        uses: -1
      - mode: value
        value: Proceed To Checkout
        index: 0
        uses: 0
      - mode: value
        value: Proceed to checkout
        index: 0
        uses: -1
      - mode: value
        value: proceed to checkout
        index: 0
        uses: -1
      - mode: text
        value: Proceed To Checkout
        index: 0
        uses: 0
