locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: id
      value: addedToCartModal
      index: 0
      uses: 2
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: add_to_cart
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Add To Cart
        index: 0
        uses: -1
      - mode: text
        value: Add to cart
        index: 0
        uses: -1
      - mode: text
        value: add to cart
        index: 0
        uses: -1
      - mode: value
        value: Add To Cart
        index: 0
        uses: -1
      - mode: value
        value: Add to cart
        index: 0
        uses: -1
      - mode: value
        value: add to cart
        index: 0
        uses: -1
      - mode: css
        value: .add-to-cart
        index: 0
        uses: 14
